const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('pet', {
  workarea: () => ipcRenderer.invoke('pet:workarea'),
  readAsset: (name) => ipcRenderer.invoke('pet:read-asset', name),
  stageAssets: () => ipcRenderer.invoke('pet:stage-assets'),
  moveBy: (dx, dy) => ipcRenderer.send('pet:move-by', dx, dy),
  setPosition: (x, y) => ipcRenderer.send('pet:set-position', x, y),
  setIgnoreMouse: (ignore) => ipcRenderer.send('pet:set-ignore-mouse', ignore),
  contextMenu: () => ipcRenderer.send('pet:context-menu'),
  getConfig: () => ipcRenderer.invoke('pet:get-config'),
  chat: (text) => ipcRenderer.invoke('pet:chat', text),
  onChatDelta: (cb) => {
    const h = (_e, d) => cb(d);
    ipcRenderer.on('pet:chat-delta', h);
    return () => ipcRenderer.removeListener('pet:chat-delta', h); // 返回取消函数
  },
  reminderAdd: (text) => ipcRenderer.invoke('pet:reminder-add', text),
  guideQuery: (text) => ipcRenderer.invoke('pet:guide-query', text),
  setScale: (s) => ipcRenderer.send('pet:set-scale', s),
  setFontSize: (px) => ipcRenderer.send('pet:set-font-size', px),
  onAction: (cb) => ipcRenderer.on('pet:action', (_e, action, ms) => cb(action, ms)),
  onGaze: (cb) => ipcRenderer.on('pet:gaze', (_e, angle) => cb(angle)),
  onScale: (cb) => ipcRenderer.on('pet:scale', (_e, s) => cb(s)),
  onReminderFired: (cb) => ipcRenderer.on('pet:reminder-fired', (_e, text) => cb(text)),
  onPush: (cb) => ipcRenderer.on('pet:push', (_e, item) => cb(item)),
  onSlouch: (cb) => ipcRenderer.on('pet:slouch', (_e, procName) => cb(procName)),
  hotfixNow: () => ipcRenderer.invoke('admin:hotfix-now'),
  hotfixLog: () => ipcRenderer.invoke('admin:hotfix-log'),
  setHotfixUrl: (url) => ipcRenderer.invoke('admin:set-hotfix-url', url),
  onHotfixUpdated: (cb) => ipcRenderer.on('hotfix:updated', (_e, info) => cb(info)),
  onCloneFade: (cb) => ipcRenderer.on('pet:clone-fade', () => cb()),
  cloneActivity: () => ipcRenderer.send('pet:clone-activity'),
  openChatWindow: (mode) => ipcRenderer.invoke('pet:open-chat-window', mode),
  getChatHistory: () => ipcRenderer.invoke('pet:chat-history'),
  onChatMode: (cb) => ipcRenderer.on('pet:chat-mode', (_e, m) => cb(m)),
  nurtureState: () => ipcRenderer.invoke('pet:nurture-state'),
  feed: (itemId) => ipcRenderer.invoke('pet:feed', itemId),
  workStart: (type) => ipcRenderer.invoke('pet:work-start', type), // 透传打工类型（此前被吞，三选一永远落默认）
  workResult: () => ipcRenderer.invoke('pet:work-result'),
  feedback: (delta) => ipcRenderer.invoke('pet:feedback', delta),
  rewardGrant: (type) => ipcRenderer.invoke('pet:reward-grant', type),
  gachaPull: (pool, n) => ipcRenderer.invoke('pet:gacha-pull', pool, n),
  exchange: (kind) => ipcRenderer.invoke('pet:exchange', kind),
  dungeonStart: (subject) => ipcRenderer.invoke('pet:dungeon-start', subject),
  dungeonQuestion: () => ipcRenderer.invoke('pet:dungeon-question'),
  dungeonSubmit: (idx) => ipcRenderer.invoke('pet:dungeon-submit', idx),
  dungeonQuit: () => ipcRenderer.invoke('pet:dungeon-quit'),
  loginBonus: () => ipcRenderer.invoke('pet:login-bonus'),
  introSeen: () => ipcRenderer.invoke('pet:intro-seen'),
  warehouseUse: (wid) => ipcRenderer.invoke('pet:warehouse-use', wid),
  mobileQr: () => ipcRenderer.invoke('pet:mobile-qr'),
  getI18n: () => ipcRenderer.invoke('pet:get-i18n'),
  onTaskDone: (cb) => ipcRenderer.on('pet:task-done', (_e, d) => cb(d)),
  onStateLow: (cb) => ipcRenderer.on('pet:state-low', (_e, d) => cb(d)),
  onWarehouseChanged: (cb) => ipcRenderer.on('pet:warehouse-changed', () => cb()),
  // ===== 管理员层（v2.4.0）：双层账号——敏感操作全部要求 PIN 解锁态，主进程侧再校验一次 =====
  adminOpen: () => ipcRenderer.send('admin:open'),
  adminMinimize: () => ipcRenderer.send('admin:minimize'),
  adminClose: () => ipcRenderer.send('admin:close'),
  adminStatus: () => ipcRenderer.invoke('admin:status'),
  adminSetupPin: (p1, p2) => ipcRenderer.invoke('admin:setup-pin', p1, p2),
  adminVerify: (pin) => ipcRenderer.invoke('admin:verify', pin),
  adminLock: () => ipcRenderer.invoke('admin:lock'),
  adminChangePin: (oldPin, p1, p2) => ipcRenderer.invoke('admin:change-pin', oldPin, p1, p2),
  adminListBackups: () => ipcRenderer.invoke('admin:list-backups'),
  adminBackupNow: () => ipcRenderer.invoke('admin:backup-now'),
  adminRestore: (name) => ipcRenderer.invoke('admin:restore', name),
  adminExport: () => ipcRenderer.invoke('admin:export'),
  adminImport: () => ipcRenderer.invoke('admin:import'),
  adminOpenSaveFolder: () => ipcRenderer.invoke('admin:open-save-folder'),
  adminOpenDevTools: (target) => ipcRenderer.invoke('admin:open-devtools', target),
  adminSetPoolUrl: (url) => ipcRenderer.invoke('admin:set-pool-url', url),
  adminEconReport: () => ipcRenderer.invoke('admin:econ-report'),
  adminEconAdjust: (kind, delta) => ipcRenderer.invoke('admin:econ-adjust', kind, delta),
  adminRedeemList: () => ipcRenderer.invoke('admin:redeem-list'),
  adminRedeemConfirm: (wid) => ipcRenderer.invoke('admin:redeem-confirm', wid),
  adminRedeemReject: (wid) => ipcRenderer.invoke('admin:redeem-reject', wid),
  adminGetLog: () => ipcRenderer.invoke('admin:get-log'),
  // ===== HUD 主窗口（v2.2.6）：数据通道复用上方 pet:* 同一套 handler，这里只补窗口控制与素材/状态订阅 =====
  hudInit: () => ipcRenderer.invoke('hud:init'),
  hudMinimize: () => ipcRenderer.send('hud:minimize'),
  hudMaximize: () => ipcRenderer.send('hud:maximize'),
  hudClose: () => ipcRenderer.send('hud:close'),
  onHudMaximized: (cb) => ipcRenderer.on('hud:maximized', (_e, v) => cb(v)),
  onHudState: (cb) => ipcRenderer.on('hud:state', (_e, st) => cb(st)),
});
